services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"     # HTTP API port
      - "50051:50051"   # gRPC port (recommended for v4 client performance)
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=            # disable all modules (good for custom embeddings)
      - DEFAULT_VECTORIZER_MODULE=none   # tell Weaviate to not auto-vectorize
      - CLUSTER_HOSTNAME=node1
      - LOG_LEVEL=info             # optional: set log level
      - GRPC_PORT=50051           # explicitly set gRPC port
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: unless-stopped        # optional: auto-restart on failure
    healthcheck:                   # optional: health check
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s